
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 21 19:12:52 GFT 2018
//----------------------------------------------------

package br.com.minic.analisadorsintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 34;
  public static final int CHAR = 16;
  public static final int EXCLAMA = 26;
  public static final int SOMA = 31;
  public static final int ABRE_CHAVE = 8;
  public static final int LITERAL_PONTO_FLUTUANTE = 36;
  public static final int DOUBLE = 15;
  public static final int FECHA_CHAVE = 9;
  public static final int LETRA_H = 14;
  public static final int INT = 3;
  public static final int VIRGULA = 39;
  public static final int PONTO = 13;
  public static final int IDENTIFICADOR = 5;
  public static final int IGUAL = 24;
  public static final int PRINTSTR = 23;
  public static final int MAIN = 4;
  public static final int IF = 18;
  public static final int RETORNO = 40;
  public static final int IGUAL_IGUAL = 28;
  public static final int PRINTINT = 22;
  public static final int EOF = 0;
  public static final int PONTO_VIRGULA = 25;
  public static final int MAIOR = 7;
  public static final int ABRE_PARENTESES = 10;
  public static final int error = 1;
  public static final int DIFERENTE_IGUAL = 27;
  public static final int INCLUDE = 2;
  public static final int LITERAL_CHAR = 37;
  public static final int MENOS = 32;
  public static final int MENOR = 6;
  public static final int LITERAL_INTEIRO = 35;
  public static final int PRINTF = 21;
  public static final int JOGO_DA_VELHA = 12;
  public static final int ELSE = 20;
  public static final int LITERAL_STRING = 38;
  public static final int WHILE = 19;
  public static final int FECHA_PARENTESES = 11;
  public static final int FLOAT = 17;
  public static final int MENOR_IGUAL = 30;
  public static final int MAIOR_IGUAL = 29;
  public static final int VEZES = 33;
}

